travis:
  secure:
    BINSTAR_TOKEN: lU2jjABXO+i+z82BHuqU3/7cplD5YuqREaGYu+Cw2w79cVEC7wWO735o/33XoluGIQ6OTAXCp+0ihffX2FYhHKFMGYbTSCCw00Op6FwhBWaqzSR6BPe1pKtwKiZZrMB6wrQgJsJNodBzLSeiV/bq/lVZg4uN9sH9Gni4yrIyQ+Fi/RY0yUMkvyb7cRGdjVbUsDT+OrWs84Vq6xJ29QJ8rOWb6yuzeOEQYaZLqjDplN/EbFhbyZnB+2uDl6EQvXorhFGorvjq+jLggv1uCcraOs1no7DVx7bswg5Y7VdGw/nmDprDKnI+bVMa/OY1gZ0vG0NmOl427fjFXn0db90y8Tmdc4TjlGBAcAr2XYeScZbz8DA+ho8soL3rAVBYu0LbIVoNSlWhY/OtF94n6CU+oQ58ahknoetzdeG//ynWykTqtvU2j4Z6XYqJ/eiBZaUojNQlfWzKLY94OAhstr3NFykqNnWPg0BMqDBnQuoLSiG+y4kEfj5GAXx+1zyCEc5nwlgDnUFgDfCkTBFQLgspc2jVng85LW9Svid9kjm9Y5x3nk6JYioqsWefhfWAspIXyuCEHUa4Y8KMSIFPsXPVd3Bhp8yQrS9gZw7BUlvJ3G08e6bTa9ddsqp98NLKfdmatL0Ssl3czTCuBm0U6n75kKbSUSiqHbfkG0kEYzuPXVk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
