travis:
  secure:
    BINSTAR_TOKEN: gqKEOzYM46wx2FGbQQhaH9Mray3lr+ybwxH0Ne5NkFXPYURpsvMmKZ1Px+ytMwvD/pIcgL0QzpAbXHEx4awEfJmKJURFJGYvilX0SWYz7CSVPE1z9LrQT0otKi0KIfEq1KfLx655PFRvvf9ooQvACUy6D4iCgvLh8r/hVJjNW4vWuP1QfvCsLpxtRrCemKa3gPW11C4oresTWxn91pG3MDsyet0mCxQ/eQWLZ/sZIcbUUmpok3mFquwsy71Li/YzaFdQT9I3qWzPKt2kfHvXDBqrf84z7iOM3jbRvjEgFXyQkNWEo6oQ8sgoh/MjxqJeeM3nLFFaLsSu4SWHyTtPb/RcZr3CR1zFl7ahLyLJcdf6SyxrK1zquKb6bh5qctGtWLt9vMxYLvt0HsPv6z49jRW+GaOJ4xze7wlssTITlZH9RTxil/ZymzavjUyESEjtCAQGtHcjKRhKJ5AuMN4NlZokE288Fs91A44HUgrU/mRGdP9RgocCRe005VDfamWslxVRFC9/9okKMAfBFxEuOBsno0du/Va0LPNNddZ4n/ziCwUyRn+/cZxLjhExCAXri0nU4HcCtMOoPBVSQH85aZaxy2kD24s+nN7RLXlsSeORNnOuamGWiRrtFhHzOrdPNlo/8gHqhVxKJSmtZUcYUf24Gs4XAEzPbzZU8Mtp3CM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
